name: Publish scheduled post

on:
  schedule:
    - cron: "0 5 * * *"
    - cron: "0 8 * * *"
    - cron: "0 12 * * *"
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Publish post
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_USERNAME: ${{ secrets.CHANNEL_USERNAME }}
        run: python publish.py
